name: Deploy on Linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Install .NET Dependencies
      run: dotnet restore ./server/server.sln

    - name: Build .NET
      run: dotnet build --configuration Release ./server/server.sln

    - name: Publish .NET
      run: dotnet publish ./server/app/app.csproj -c Release -o ./webapp

    - name: Upload .NET Web App
      uses: actions/upload-artifact@v4
      with:
        name: back-end
        path: webapp/*

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
        cache-dependency-path: client/package-lock.json

    - name: Install Node.js Dependencies
      working-directory: ./client
      run: npm install

    - name: Build Vue Web App
      working-directory: ./client
      run: npm run build

    - name: Upload Vue Web App
      uses: actions/upload-artifact@v4
      with:
        name: front-end
        path: client/dist/*